### ISSUE TITLE
Sandbox Configuration HowTo

### ISSUE THREAD

**Issue by vpupkin** [tony1223/zkfiddle#167]
Hello Tony,
i am currently on configuring the zkfiddle on my local. All point from https://github.com/tony1223/zkfiddle/wiki/How-to-setup-developing-environment till part [ Sandbox ] work fine! Many thank  for nice doc. Could you please publish your step-by-step-how-to for the latest point. I want to reproduce your success on my dev-env ASAP!

PS
10x 4 zkfiddle  - greate job! Pls dont stop it ;)

**Comment by tony1223** [comment]
Hi ,

It's glad to get some questions from users for me. :)

I updated the document ,and hoped that's clear enough for your.

Let me know if you need further assistance.

https://github.com/tony1223/zkfiddle/wiki/How-to-setup-developing-environment
https://github.com/tony1223/zkfiddle-sandbox/wiki/How-to-setup-developing-environment

About the fiddle-sandbox , it's just need to write the conf.xml and to prepare
the jars.

Basically the reason that we need a "conf.xml" file to set up a sandbox is
,
you have to tell sandboxs what the jars (or in other hand , the classpaths
) is .

For minimize memory usage , we could start multiple web context in one sandbox ,
and we have to setup each context's classpaths , zk version and zk theme
for them.

Also the sandbox need to know where's the datahandler is ,  then we could
send the information to datahandler ,
so it could know how to show the sandbox information in datahandler and
where's the url to be redirected when user select a sandbox and run samples.

Note:
because we allow user to write and run their own java code in sandbox ,
so there's still some security issue .

I use guest accounts to run the sandbox in zkfiddle production so it won't
be a big issue for me ,
but if you want to build a public website with it , you should keep the
security issues in mind.

Yep , I will keep working on fiddle , it's still a lot of things we could
do in the fiddle. :)

2011/11/30 vpupkin <
reply@reply.github.com

**Comment by tony1223** [comment]
Close this first , let me know if you need further assistance.
