### ISSUE TITLE
Subject / category / version / comitter

### ISSUE THREAD

**Issue by terrytornado** [tony1223/zkfiddle#31]
Hi Tony,

without looking in the codes, is it possible to make an overview list with the info data like the title.

thanks
Stephan

PS: zkfiddle is a very great idea. Go on with that.

**Comment by tmillsclare** [comment]
I like this idea, if someone adds a sample to zkfiddle could we somehow link their commit to a public profile?

**Comment by tony1223** [comment]
You are so kind , terrytornado . (btw , thanks for your contribute to our forum in such a long time. ;p )

For the committer part, yes,  I will place it to milestone 1.1.0 , 
we will integrate with FB connect and open id service  instead filling boring register form,
I wanna to try to write some ZK components to handle this. 

About the version/category part , I will handle them as a special tag , it's already in the schedule.

For a subject , currently we have a title , that's all we need I think.

I think it's better to let user write some information on their own blog , 
instead of to make fiddle too complicated, fiddle is only a platform to show code and run code online. 

And it should be easy to integrate with other site as a iframe widget,
my next plan in milestone 1.2 is to make it integrate with our ZK forum . 

(I am also the maintainer for ZK forum , although I didn't have much time to handle it. :-| )

Anyway , let's keep moving on. ;)

**Comment by tony1223** [comment]
We just finished the user part in yesterday.
In next version that I have done, we will use tag list and user list to handle this.

Currently I think it's useless to list a full case list since it's kind of code paste serivice , 
not every sample is good enough or worth to read it.

But it still might be considered in future.

I am still working for two directions , one for easy to create a sample , another one for easy to find a useful sample.

So I am going to close this issue now , 
if you have any ideas related to this , please feel free to post a new issue. Thanks a lot. :)
