### ISSUE TITLE
image resource design

### ISSUE THREAD

**Issue by tony1223** [tony1223/zkfiddle#92]
Let me think if we need to upload some binary file , like image ,
what's the best solution to handle it in following part or anything we not considered yet.

1.minimized file storage
2.one case or one resource can't depend on other resource or other case.
3.Easy to link with both sandbox and datahandler.  (in minimized traffic if possible , at least it need to be reasonable.)

This one is more critical one and we could take more time to design and think , just left a record here first.

**Comment by zanyking** [comment]
I think, the simplest solution is:

For every uploaded media, we store it as a record in DB(Table:
media_resource), because the media it's self shouldn't be huge.
for user who just want to upload a media to fiddle for sample code purpose,
I think this is a reasonable assumption, we can limited the uploaded files
size.

The media_resource schema  might be: (UUID,  blob, mime_type, name, hash,
caseid)

at the resource table, we simply store the UUID of that media in
media_resource table at the content column.
So when we found a resource's type is other then text, we fetch it from
media_resource.(can use an EHcache in front)

and because for any version of the cases, the resource entry will just store
the media_resource's uuid  so the size would be small, and for any different
version, the resource can point to different UUID of  media_resources.

2011/7/15 tony1223 <
reply@reply.github.com>

**Comment by tony1223** [comment]
Currently make this as pending , and use #128 to handle this first.

Let's discuss this implementation more.

**Comment by tony1223** [comment]
Close this first.
